theme = "codemonkey"
baseurl = "http://joelthecodemonkey.com:1313/"
languageCode = "en-us"
title = "Code Shinannigans and fun projects"

[params]
    bannerText = "Make Something"
    title = "Joel the Code Monkey"

[params.home]
    text = "Home"
    tooltip = "Homepage"
    icon = "fa-home"

[params.github]
    text = "Github"
    tooltip = "Github"
    link = "https://github.com/jdollar"
    icon = "fa-github"

[params.blog]
    tooltip = "Blogs"
    text = "Blog"
    icon = "fa-list"
    link = "/code/"
