# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Codemonkey"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Theme generated for the joelthecodemonkey.com website"
homepage = "http://joelthecodemonkey.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Joel Dollarhide"
  homepage = "http://joelthecodemonkey.com/"

# If porting an existing theme
[original]
  name = "Joel Dollarhide"
  homepage = "http://joelthecodemonkey.com/"
  repo = ""
